const express = require("express");
const router = express.Router();
const customer = require("./Routes/Customer");
const restaurant = require("./Routes/Restaurant");
const item = require("./Routes/Item");
const cart = require("./Routes/Cart");
router.use("/customer", customer);
router.use("/restaurant", restaurant);
router.use("/item", item);
router.use("/cart", cart);
module.exports = router;
